/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PARSER;

import org.junit.Test;
import static org.junit.Assert.*;

public class ParserTest {
    @Test public void testSomeLibraryMethod() {
        PDDL pddl = new PDDL("test");
        assertTrue("someLibraryMethod should return 'true'", pddl.bt());
    }
}
